In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split

In [2]:
data=sns.load_dataset('iris')

In [3]:
data.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df_x=features=data[['sepal_length','sepal_width' , 'petal_length','petal_width']]
df_y=target=data['species']

In [5]:
x_train , x_test , y_train , y_test= train_test_split(df_x,df_y,test_size=0.33 , random_state=42)

In [6]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [7]:
x_train

array([[-0.13835603, -0.26550845,  0.22229072,  0.10894943],
       [ 2.14752625, -0.02631165,  1.61160773,  1.18499319],
       [-0.25866563, -0.02631165,  0.39595535,  0.37796037],
       [-0.8602136 ,  1.16967238, -1.39857913, -1.37061074],
       [ 2.26783585, -0.50470526,  1.66949594,  1.05048772],
       [-0.01804644, -0.74390206,  0.16440251, -0.29456698],
       [-0.739904  ,  0.93047557, -1.39857913, -1.37061074],
       [-0.98052319,  1.16967238, -1.45646733, -1.23610527],
       [-0.8602136 ,  1.88726279, -1.10913808, -1.1015998 ],
       [-0.98052319, -2.4182797 , -0.18292674, -0.29456698],
       [ 0.58350153, -0.74390206,  0.62750818,  0.78147678],
       [-1.22114238,  0.93047557, -1.10913808, -1.37061074],
       [-0.98052319, -0.02631165, -1.28280271, -1.37061074],
       [-0.8602136 ,  0.69127877, -1.2249145 , -0.96709433],
       [-0.25866563, -0.74390206,  0.22229072,  0.10894943],
       [-0.8602136 ,  0.93047557, -1.34069092, -1.37061074],
       [-0.13835603, -0.

In [8]:
from sklearn.naive_bayes import GaussianNB
nvclassifier=GaussianNB()
nvclassifier.fit(x_train,y_train)

GaussianNB()

In [9]:
y_predict=nvclassifier.predict(x_test)
print(y_predict)

['versicolor' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'versicolor' 'virginica' 'versicolor' 'versicolor' 'virginica' 'setosa'
 'setosa' 'setosa' 'setosa' 'virginica' 'virginica' 'versicolor'
 'versicolor' 'virginica' 'setosa' 'virginica' 'setosa' 'virginica'
 'virginica' 'virginica' 'virginica' 'virginica' 'setosa' 'setosa'
 'setosa' 'setosa' 'versicolor' 'setosa' 'setosa' 'virginica' 'versicolor'
 'setosa' 'setosa' 'setosa' 'virginica' 'versicolor' 'versicolor' 'setosa'
 'setosa' 'versicolor' 'versicolor' 'virginica' 'versicolor' 'virginica']


In [10]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
print(cm)

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]


In [11]:
a=cm.shape
corrPred=0
falsepred=0
for row in range(a[0]):
    for c in range(a[1]):
        if row==c:
            corrPred+=cm[row,c]
        else:
            falsepred+=cm[row,c]
print("Correct predictions:",corrPred)
print("False predictions",falsepred)
print("\n\nAccuracy of Naive Bayes classification is :",corrPred/(cm.sum()))

Correct predictions: 48
False predictions 2


Accuracy of Naive Bayes classification is : 0.96


In [12]:
from sklearn.metrics import classification_report
cr=classification_report(y_test,y_predict)
print(cr)

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       0.93      0.93      0.93        15
   virginica       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50

